app/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.dashboard.views import DashboardView
from core.homepage.views import IndexView
from core.login.views import LoginFormView2, LoginFormView

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404
from core.erp.views.dashboard.views import page_not_found404

handler404 = page_not_found404

urlpatterns = [
    # path('', IndexView.as_view(), name='index'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('erp/', include(('core.erp.urls', 'erp'))),
    path('user/', include(('core.user.urls', 'user'))),
    path('login/', include(('core.login.urls', 'accounts'))),
    path('reports/', include(('core.reports.urls', 'reports'))),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/user/urls.py
from django.urls import path
from core.user.views import UserListView, UserCreateView, UserUpdateView, UserDeleteView, UserChangeGroup, \
    UserProfileView, UserChangePasswordView

app_name = 'user'

urlpatterns = [
    #user
    path('list/', UserListView.as_view(), name='user_listview'),
    path('create/', UserCreateView.as_view(), name='user_createview'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_updateview'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_deleteview'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

app/templates/hzt/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'hzt/header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}
    {% endblock %}
    <script>
        //MESSAGES
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>'
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

app/templates/hzt/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <div class="container">
        <a href="{% url 'dashboard' %}" class="navbar-brand">
            <img src="{% static 'img/logo_horus.ico' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Hades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'dashboard' %}" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'erp:category_listview' %}" class="dropdown-item"><i
                                class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="{% url 'erp:product_listview' %}" class="dropdown-item"><i
                                class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="{% url 'erp:client_listview' %}" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="{% url 'erp:sale_listview' %}" class="dropdown-item"><i
                                class="fas fa-shopping-cart"></i> Ventas</a></li>
                        <li><a href="{% url 'reports:sale_reportview' %}" class="dropdown-item"><i
                                class="fas fa-chart-bar"></i> Reporte de Ventas</a></li>
                        <li><a href="{% url 'user:user_listview' %}" class="dropdown-item"><i
                                class="fas fa-user-friends"></i> Usuarios</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            {% if request.user.groups.all %}
                <li class="nav-item dropdown show">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                       class="nav-link
                        {% if request.user.groups.count > 1 %}dropdown-toggle{% endif %}
                        ">{{ request.session.group.name }}</a>
                    {# Si el numero de grupos del usuario es mayor a uno se muestre el dropdown, sino no #}
                    {% if request.user.groups.count > 1 %}
                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                            style="left: 0px; right: inherit;">
                            <!-- Listado de grupos del usuario -->
                            {% for group in  request.user.groups.all %}
                                {% if group.id != request.session.group.id %}
                                    <li><a href="{% url 'user:user_change_group' group.id %}"
                                           class="dropdown-item">{{ group.name }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="fas fa-users-cog"></i> {{ request.user.get_full_name }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header">
                        Último Acceso: {{ request.user.last_login }}
                    </span>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                        <i class="fas fa-edit mr-2"></i> Editar perfil
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                        <i class="fas fa-lock mr-2"></i> Editar password
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown-footer">
                        <p>Este sistema te permitira realizar diferentes actividades</p>
                    </a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">
                    <i class="fas fa-power-off" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>